# Generated by Django 5.1.1 on 2024-09-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_search', '0003_restaurant_place_id_alter_restaurant_cuisine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='place_id',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(max_length=100),
        ),
    ]
